"""schema inicial

Revision ID: 00b9140141e9
Revises: 
Create Date: 2026-09-18 00:41:38.443417

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '00b9140141e9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centro_distribucion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('distancia_km', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('distancia_min', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direccion')
    )
    op.create_table('clase_licencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clase', sa.Enum('A1', 'A2', 'A3', 'A4', 'A5', 'B', 'C', 'D', 'E', 'F', name='licenciaclase'), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clase')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rut', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail'),
    sa.UniqueConstraint('rut'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('conductor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombres', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apellidos', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('tipo_camion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo')
    )
    op.create_table('camion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patente', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_tipo_camion', sa.Integer(), nullable=False),
    sa.Column('peso_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volumen_m3', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_camion'], ['tipo_camion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patente')
    )
    op.create_table('carga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_centro', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('CREADO', 'EN_RUTA', 'CANCELADA', name='cargaestado'), nullable=False),
    sa.ForeignKeyConstraint(['id_centro'], ['centro_distribucion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clase_licencia_tipo_camion',
    sa.Column('id_clase', sa.Integer(), nullable=False),
    sa.Column('id_tipo_camion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_clase'], ['clase_licencia.id'], ),
    sa.ForeignKeyConstraint(['id_tipo_camion'], ['tipo_camion.id'], ),
    sa.PrimaryKeyConstraint('id_clase', 'id_tipo_camion')
    )
    op.create_table('cliente_centro',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_centro', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_centro'], ['centro_distribucion.id'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id_cliente', 'id_centro')
    )
    op.create_table('licencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_conductor', sa.Integer(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_conductor'], ['conductor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('peso_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volumen_m3', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ventana_inicio', sa.DateTime(), nullable=False),
    sa.Column('ventana_fin', sa.DateTime(), nullable=False),
    sa.Column('tipo_mercaderia', sa.Enum('GENERAL', 'REFRIGERADA', 'PELIGROSA', 'FRAGIL', name='mercaderiatipo'), nullable=False),
    sa.Column('estado', sa.Enum('EN_ESPERA', 'TRANSITO', 'ENTREGADO', 'CANCELADO', name='pedidoestado'), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_camion', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('SOAP', 'RT', 'PC', 'PADRON', 'CEC', name='documentotipo'), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_camion'], ['camion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('licencia_clase',
    sa.Column('id_licencia', sa.Integer(), nullable=False),
    sa.Column('id_clase', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_clase'], ['clase_licencia.id'], ),
    sa.ForeignKeyConstraint(['id_licencia'], ['licencia.id'], ),
    sa.PrimaryKeyConstraint('id_licencia', 'id_clase')
    )
    op.create_table('pedido_carga',
    sa.Column('id_carga', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_carga'], ['carga.id'], ),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id_carga', 'id_pedido')
    )
    op.create_table('viaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_conductor', sa.Integer(), nullable=False),
    sa.Column('id_camion', sa.Integer(), nullable=False),
    sa.Column('id_carga', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_camion'], ['camion.id'], ),
    sa.ForeignKeyConstraint(['id_carga'], ['carga.id'], ),
    sa.ForeignKeyConstraint(['id_conductor'], ['conductor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viaje')
    op.drop_table('pedido_carga')
    op.drop_table('licencia_clase')
    op.drop_table('documento')
    op.drop_table('pedido')
    op.drop_table('licencia')
    op.drop_table('cliente_centro')
    op.drop_table('clase_licencia_tipo_camion')
    op.drop_table('carga')
    op.drop_table('camion')
    op.drop_table('tipo_camion')
    op.drop_table('conductor')
    op.drop_table('cliente')
    op.drop_table('clase_licencia')
    op.drop_table('centro_distribucion')

    for enum_name in ("licenciaclase", "pedidoestado", "cargaestado", "mercaderiatipo", "documentotipo"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # ### end Alembic commands ###
