"""viaje fecha_cancelacion

Revision ID: 583aa6934749
Revises: c7e3bb2cc13b
Create Date: 2026-10-02 00:49:33.686736

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '583aa6934749'
down_revision: str | None = 'c7e3bb2cc13b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viaje', sa.Column('fecha_cancelacion', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('viaje_id_carga_key'), 'viaje', type_='unique')
    op.create_index('viaje_id_carga_vigente_key', 'viaje', ['id_carga'], unique=True, postgresql_where=sa.text('fecha_cancelacion IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('viaje_id_carga_vigente_key', table_name='viaje', postgresql_where=sa.text('fecha_cancelacion IS NULL'))
    op.create_unique_constraint(op.f('viaje_id_carga_key'), 'viaje', ['id_carga'], postgresql_nulls_not_distinct=False)
    op.drop_column('viaje', 'fecha_cancelacion')
    # ### end Alembic commands ###
