"""rf101_atributos_camion

Revision ID: 687c5988c3bc
Revises: 39ccd34b8fc7
Create Date: 2026-09-23 00:23:09.758077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '687c5988c3bc'
down_revision: Union[str, None] = '39ccd34b8fc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Agregar columnas con server_default para soportar filas existentes
    op.add_column('camion', sa.Column('marca', sqlmodel.sql.sqltypes.AutoString(), server_default='Genérica', nullable=False))
    op.add_column('camion', sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(), server_default='Genérico', nullable=False))
    op.add_column('camion', sa.Column('anio', sa.Integer(), server_default='2022', nullable=False))
    op.add_column('camion', sa.Column('rendimiento_base_km_l', sa.Numeric(precision=5, scale=2), server_default='3.00', nullable=False))
    op.add_column('camion', sa.Column('kilometraje_actual', sa.Integer(), server_default='0', nullable=False))
    op.add_column('camion', sa.Column('activo', sa.Boolean(), server_default='true', nullable=False))

    # 2. Poblar con datos realistas para los 3 camiones existentes
    conn = op.get_bind()
    conn.execute(sa.text("""
        UPDATE camion SET 
            marca = 'Volvo', 
            modelo = 'FH 500', 
            anio = 2023, 
            rendimiento_base_km_l = 2.80, 
            kilometraje_actual = 142500, 
            activo = true 
        WHERE patente = 'ABCD-12'
    """))
    conn.execute(sa.text("""
        UPDATE camion SET 
            marca = 'Scania', 
            modelo = 'R450', 
            anio = 2022, 
            rendimiento_base_km_l = 2.40, 
            kilometraje_actual = 210300, 
            activo = true 
        WHERE patente = 'EFGH-34'
    """))
    conn.execute(sa.text("""
        UPDATE camion SET 
            marca = 'Mercedes-Benz', 
            modelo = 'Atego 1018', 
            anio = 2021, 
            rendimiento_base_km_l = 6.20, 
            kilometraje_actual = 89100, 
            activo = true 
        WHERE patente = 'IJKL-56'
    """))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('camion', 'activo')
    op.drop_column('camion', 'kilometraje_actual')
    op.drop_column('camion', 'rendimiento_base_km_l')
    op.drop_column('camion', 'anio')
    op.drop_column('camion', 'modelo')
    op.drop_column('camion', 'marca')
    # ### end Alembic commands ###
