"""Add entrega fields to Pedido

Revision ID: 7924965435fc
Revises: 2c953ddd353b
Create Date: 2026-09-30 00:02:58.190394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7924965435fc'
down_revision: Union[str, None] = '2c953ddd353b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('fecha_entrega', sa.DateTime(), nullable=True))
    op.add_column('pedido', sa.Column('receptor', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('pedido', sa.Column('observaciones', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedido', 'observaciones')
    op.drop_column('pedido', 'receptor')
    op.drop_column('pedido', 'fecha_entrega')
    # ### end Alembic commands ###
